@startuml
package "SubscriptionService" {
    skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
    }

    class Customer {
        -name: string
        -money: int
    }

    interface Service {
        +Subscribe(Customer): void
    }

    class ServiceProxy {
        -Service: Service
        +Subscribe(Customer): void
    }

    class MusicService {
        -customers: Customer[]
        +Subscribe(Customer)
    }

    Customer -right-> Service
    MusicService .up.|> Service
    ServiceProxy .up.|> Service
    ServiceProxy o-right-> MusicService

} 
@enduml